version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"               
    volumes:
      - .:/app                   
    environment:
      APP_ENV: "local"
      APP_DEBUG: "true"
      LOG_CHANNEL: "stderr"
      DB_CONNECTION: "pgsql"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: "notes_db"
      DB_USERNAME: "notes_user"
      DB_PASSWORD: "notes_password"
    working_dir: /app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
